services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - iot
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  
  telegraf:
    image: rdautov/trust-agent:0.1
    container_name: trust-agent
    privileged: true
    user: root 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    depends_on:
      - mosquitto
    networks:
      - iot 

networks:
  iot: